import { launch, open } from "./lib.mjs";
const b = await launch();
let bad = 0; const ok = (c, m) => { if (!c) bad++; console.log(c ? "ok  " : "FAIL", m); };
const { page: p, errors } = await open(b, "schedule", { width: 1366, height: 900 });
await p.getByRole("button", { name: "Place a person" }).click();
await p.getByRole("dialog").getByRole("button", { name: /Lena Sorensen/ }).click(); await p.waitForTimeout(300);
const cells = p.locator("[role=gridcell].ring-ok");
await cells.first().scrollIntoViewIfNeeded(); await cells.first().click(); await p.waitForTimeout(300);
await cells.first().click(); await p.waitForTimeout(300);
await p.keyboard.press("Escape");
await p.getByRole("button", { name: "File" }).click(); await p.getByRole("menuitem", { name: /Recent changes/ }).click(); await p.waitForTimeout(400);
const d = p.getByRole("dialog");
const items = await d.getByRole("listitem").allInnerTexts();
ok(items.length >= 2, `history lists ${items.length} entries: ${items.slice(0, 2).map(t => t.split("\n")[0]).join(" | ")}`);
ok(/Lena scheduled at/.test(items[0] ?? ""), "newest is described in words");
const num = async () => (await p.locator(`section[aria-label="Month status"] button`).first().innerText()).trim();
const lastBefore = await num();
await d.getByRole("button", { name: /^Undo 2$/ }).click(); await p.waitForTimeout(500);
const after = await num();
ok(lastBefore !== after, `undo 2 steps changed the problem count (${lastBefore} → ${after})`);
ok(errors.length === 0, `no errors ${errors.join(";")}`);
console.log(bad ? `${bad} FAILURES` : "HISTORY OK");
await b.close();
