/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HolidaysRouteImport } from './routes/holidays'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PrintRouteImport } from './routes/print'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as StyleRouteImport } from './routes/style'
import { Route as TimeOffRouteImport } from './routes/time-off'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysRoute = HolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleRoute = StyleRouteImport.update({
  id: '/style',
  path: '/style',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeOffRoute = TimeOffRouteImport.update({
  id: '/time-off',
  path: '/time-off',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/holidays': typeof HolidaysRoute
  '/lists': typeof ListsRoute
  '/people': typeof PeopleRoute
  '/print': typeof PrintRoute
  '/schedule': typeof ScheduleRoute
  '/stores': typeof StoresRoute
  '/style': typeof StyleRoute
  '/time-off': typeof TimeOffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/holidays': typeof HolidaysRoute
  '/lists': typeof ListsRoute
  '/people': typeof PeopleRoute
  '/print': typeof PrintRoute
  '/schedule': typeof ScheduleRoute
  '/stores': typeof StoresRoute
  '/style': typeof StyleRoute
  '/time-off': typeof TimeOffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/holidays': typeof HolidaysRoute
  '/lists': typeof ListsRoute
  '/people': typeof PeopleRoute
  '/print': typeof PrintRoute
  '/schedule': typeof ScheduleRoute
  '/stores': typeof StoresRoute
  '/style': typeof StyleRoute
  '/time-off': typeof TimeOffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/holidays'
    | '/lists'
    | '/people'
    | '/print'
    | '/schedule'
    | '/stores'
    | '/style'
    | '/time-off'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/holidays'
    | '/lists'
    | '/people'
    | '/print'
    | '/schedule'
    | '/stores'
    | '/style'
    | '/time-off'
  id:
    | '__root__'
    | '/'
    | '/holidays'
    | '/lists'
    | '/people'
    | '/print'
    | '/schedule'
    | '/stores'
    | '/style'
    | '/time-off'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HolidaysRoute: typeof HolidaysRoute
  ListsRoute: typeof ListsRoute
  PeopleRoute: typeof PeopleRoute
  PrintRoute: typeof PrintRoute
  ScheduleRoute: typeof ScheduleRoute
  StoresRoute: typeof StoresRoute
  StyleRoute: typeof StyleRoute
  TimeOffRoute: typeof TimeOffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays': {
      id: '/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof HolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style': {
      id: '/style'
      path: '/style'
      fullPath: '/style'
      preLoaderRoute: typeof StyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-off': {
      id: '/time-off'
      path: '/time-off'
      fullPath: '/time-off'
      preLoaderRoute: typeof TimeOffRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HolidaysRoute: HolidaysRoute,
  ListsRoute: ListsRoute,
  PeopleRoute: PeopleRoute,
  PrintRoute: PrintRoute,
  ScheduleRoute: ScheduleRoute,
  StoresRoute: StoresRoute,
  StyleRoute: StyleRoute,
  TimeOffRoute: TimeOffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
